apiVersion: v1
kind: Service
metadata:
  name: ui-discovery-service
  labels:
    app: ui-discovery
spec:
  selector:
    app: ui-discovery
  ports:
    - protocol: TCP
      port: 80        # External port exposed by the service
      targetPort: 8081 # Port where your Spring Boot app is listening inside the pod
  type: NodePort  # Type of service (use NodePort or ClusterIP if needed)
