apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-discovery
  template:
    metadata:
      labels:
        app: ui-discovery
    spec:
      containers:
        - name: ui-discovery
          image: iamjoydevdas/ui-discovery:latest  # Replace with your Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8081  # Port where Spring Boot is running
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"