spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user-api/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products-api/**
        - id: locations-service
          uri: http://localhost:8081
          predicates:
            - Path=/locations-api/**
        - id: orders-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders-api/**

server:
  port: 9999